/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhiteNoiseRouteImport } from './routes/white-noise'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BabyRouteImport } from './routes/baby'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const WhiteNoiseRoute = WhiteNoiseRouteImport.update({
  id: '/white-noise',
  path: '/white-noise',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyRoute = BabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/baby': typeof BabyRoute
  '/favorites': typeof FavoritesRoute
  '/language': typeof LanguageRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/survey': typeof SurveyRoute
  '/white-noise': typeof WhiteNoiseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/baby': typeof BabyRoute
  '/favorites': typeof FavoritesRoute
  '/language': typeof LanguageRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/survey': typeof SurveyRoute
  '/white-noise': typeof WhiteNoiseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/baby': typeof BabyRoute
  '/favorites': typeof FavoritesRoute
  '/language': typeof LanguageRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/survey': typeof SurveyRoute
  '/white-noise': typeof WhiteNoiseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/baby'
    | '/favorites'
    | '/language'
    | '/library'
    | '/onboarding'
    | '/player'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/sleep'
    | '/survey'
    | '/white-noise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/baby'
    | '/favorites'
    | '/language'
    | '/library'
    | '/onboarding'
    | '/player'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/sleep'
    | '/survey'
    | '/white-noise'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/baby'
    | '/favorites'
    | '/language'
    | '/library'
    | '/onboarding'
    | '/player'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/sleep'
    | '/survey'
    | '/white-noise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BabyRoute: typeof BabyRoute
  FavoritesRoute: typeof FavoritesRoute
  LanguageRoute: typeof LanguageRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  PlayerRoute: typeof PlayerRoute
  ProfileRoute: typeof ProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SleepRoute: typeof SleepRoute
  SurveyRoute: typeof SurveyRoute
  WhiteNoiseRoute: typeof WhiteNoiseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/white-noise': {
      id: '/white-noise'
      path: '/white-noise'
      fullPath: '/white-noise'
      preLoaderRoute: typeof WhiteNoiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby': {
      id: '/baby'
      path: '/baby'
      fullPath: '/baby'
      preLoaderRoute: typeof BabyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BabyRoute: BabyRoute,
  FavoritesRoute: FavoritesRoute,
  LanguageRoute: LanguageRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  PlayerRoute: PlayerRoute,
  ProfileRoute: ProfileRoute,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SleepRoute: SleepRoute,
  SurveyRoute: SurveyRoute,
  WhiteNoiseRoute: WhiteNoiseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
